### ISSUE TITLE
Release 0.1.0

### ISSUE THREAD

**Issue by theskumar** [pydelhi/pydelhi.github.io#1]
__Goal:__ 

- Setup and release minimal website for further community contribution.

----

- [x] setup gh-pages (master branch is used, to setup organisational level domain)
- [x] ~~setup Travis CI for auto-deployment (not needed)~~
- [x] setup DNS for pydelhi.org 
- [x] Decide/add site color palette and overall theme of website. 

Feature Requests goes as comments below and should be added here upon consensus.

**Comment by mgill25** [comment]
Perhaps make a separate issue, but I'd like to see more discussion on pages regarding the specific agenda of the organization and what are the activities that the org will commit itself to.

**Comment by theskumar** [comment]
I'm planning to have basic html page up and running and then let it evolve as time passes and as people feel the need to add different functionality.

**Comment by aktech** [comment]
Lets use some jekyll theme, after customizing it.

**Comment by mgill25** [comment]
Not that I'm dogmatic about it, but maybe something written in Python? :)

**Comment by aktech** [comment]
Though, I meant that just for up and running purpose.

> Not that I'm dogmatic about it, but maybe something written in Python? :)

+1

**Comment by vinaykrdahiya** [comment]
I certainly agree with @theskumar that the priority here is to atleast put a face to organisation.
Since we need to submit proposal for Pycon2016 we need some quick and dirty solution so that we get the wheel moving.
As and when the time comes we can evolve the website.
@mgill25 Calling ourselves organisation is quite early we are not yet a fully functioning community we have a long way to go.

**Comment by theskumar** [comment]
Guys, the homepage of pydelhi.org is up, which I think is enough for v0.1.0 release. Have a look at https://pydelhi.org and also at the source code. 

The homepage or you can say root of the pydelhi.org is going to be simple static html hosted on Github. 

__How to create host new things under banner of pydelhi.org:__

- A repo will be created under `pydelhi` github organisation, you need to publish `gh-pages` branch in that repo. The content in that branch will automatically available at `https://pydelhi.org/<repo_name>`
- If that sub-site requires, dynamic content you are encouraged to create/host json api on the platform/language of you choice.
- If the purpose is still not solved, shout out in the mailing for an independent sub-domain under `pydelhi.org` along with `CNAME` or `A` record details, anyone with access to pydelhi.org DNS will be able to help you out.
- Send a pull request to add link/reference to the new thing that you created at https://github.com/pydelhi/pydelhi.github.io

**Comment by bhanuvrat** [comment]
@theskumar looks great ... does the job ... excellent.

**Comment by aktech** [comment]
@theskumar 
Good Job!  :+1:

**Comment by dusual** [comment]
@mgill25  I agree would love a python solution but @theskumar did a great job of getting us started. Its on github so we can just update using a pull request. I would love to use nikola  for this in future.
https://getnikola.com/

**Comment by bhanuvrat** [comment]
@dusual 
for a single page information center, _this_ looks awesome ...

What more things are we going to put in here? ideas?

**Comment by theskumar** [comment]
Let's take up the discussion on new features here: https://github.com/pydelhi/pydelhi.github.io/issues/3

For features like blogging, we can create a new repo called `gh:pydlehi/blog` and it will available at `pydelhi.org/blog/`. Personally I will prefer the root repo i.e. pydelhi.github.io not use any tooling (similar thoughts as text editor vs IDE). Let's keep it simple?
