### ISSUE TITLE
Telegram link of pydelhi volunteers group

### ISSUE THREAD

**Issue by theparadoxer02** [pydelhi/pydelhi.github.io#28]
#27 During sharing the ideas of  Pycon and **Pydelhi Conf** ,i thought it would be helpful to provide directly the telegram link  on the website where discussion happens for further plans and if any wish to in touch he can easily be.

**Comment by theskumar** [comment]
Thanks for creating this, telegram link is live now.

<img width="344" alt="pasted_image_03_03_17__6_11_am" src="https://cloud.githubusercontent.com/assets/236356/23533588/b56fd83c-ffd8-11e6-98c8-141c133d6636.png">
