### ISSUE TITLE
Add sponsors widget to home from Meetup Page

### ISSUE THREAD

**Issue by theskumar** [pydelhi/pydelhi.github.io#29]
Use meetup api https://www.meetup.com/meetup_api/docs/2/groups/ to fetch sponsors list and display all the sponsors and info after `community partner` section.

![image](https://cloud.githubusercontent.com/assets/236356/23533834/0ab45682-ffda-11e6-84ad-dd18e45dc6f7.png)

**Comment by ATB00ker** [comment]
Is this issue solved? Because i don't see any sponsors in the main home screen!

**Comment by theskumar** [comment]
No, the feature is still open for implementation. Would you like to try it out?

**Comment by ATB00ker** [comment]
Sure. Though, I have never worked with API and Javascript, So, I'll take some time.

**Comment by ATB00ker** [comment]
I am using my private API key to make request! Is there a pydelhi page registered for using APIs or should i continue with mine!?

**Comment by theskumar** [comment]
> I am using my private API key to make request! Is there a pydelhi page registered for using APIs or should i continue with mine!?

No page registered and don't use you own key or any key can't be added which become public. See if you can use `jsonp` format. Checkout the code used to fetch next meetup details on homepage. If it doesn't work we might need to setup a server side solution to fetch data.

**Comment by ATB00ker** [comment]
I tried manipulating the existing code but "message:"Invalid signature"";
Now i am new to this and i might be doing something wrong but i am unable to get authentication!
