### ISSUE TITLE
Add rss feed widget from /blog

### ISSUE THREAD

**Issue by theskumar** [pydelhi/pydelhi.github.io#30]
Using javascript only fetch and display latest blog articles summary from https://pydelhi.org/blog/feeds/rss.xml

It should:
- have section title as 'Latest Articles'
- be display after the 'next-meetup` section.
- each item should contain 'title' and 'summary' (trimmed to 80chars) max. linking to blog page.

Library that can be used:
- (with jquery plugin)https://github.com/sdepold/jquery-rss
- (without plugin) http://stackoverflow.com/a/10943610/782901

**Comment by kartikanand** [comment]
If nobody is working on this, I would like to take this up

**Comment by theskumar** [comment]
Please go ahead.

On Mar 19, 2018 9:21 AM, "Kartik Anand" <notifications@github.com> wrote:

If nobody is working on this, I would like to take this up

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/pydelhi/pydelhi.github.io/issues/30#issuecomment-374093752>,
or mute the thread

**Comment by kartikanand** [comment]
Hey Saurabh,

I've done some changes in my local fork. I've added the author as well, it's always good to give credit :)

Moreover, 80 characters seemed pretty short to me, right now I've set the limit to 180 characters, and three latest posts at a time.

You can view the changed site here:
http://www.kartikanand.com/pydelhi.github.io/

Let me know about your suggestions and feedback. Once we close on the style, I'll generate a PR

Thanks,
Kartik

**Comment by theskumar** [comment]
@kartikanand this looks good. It can utilize some styling to make it look cool.

![image](https://user-images.githubusercontent.com/236356/37639136-356cbf7a-2c36-11e8-8a60-bd5d31ed561e.png)

Something like this is what I've in mind. Unless you have better idea.

**Comment by theskumar** [comment]
Here is the overall look.

![image](https://user-images.githubusercontent.com/236356/37639207-7f82f480-2c36-11e8-832f-ba87903233ca.png)

**Comment by theskumar** [comment]
@kartikanand create a pull-request and/or give me write access to you repo, so can make the changes to the code.

**Comment by kartikanand** [comment]
Sure I'll do a pull request for it.
