### ISSUE TITLE
Contributing guide

### ISSUE THREAD

**Issue by akshayaurora** [pydelhi/pydelhi.github.io#41]
Repo needs instructions for new users on howto contribute `contribute.md`

**Comment by satyaakam** [comment]
There are lots of good examples  i am checking out 

https://gist.github.com/PurpleBooth/b24679402957c63ec426
https://github.com/atom/atom/blob/master/CONTRIBUTING.md
https://github.com/rails/rails/blob/master/CONTRIBUTING.md
https://github.com/opengovernment/opengovernment/blob/master/CONTRIBUTING.md
