### ISSUE TITLE
Add mailing list guidelines 

### ISSUE THREAD

**Issue by satyaakam** [pydelhi/pydelhi.github.io#6]
mix these two and make a one which is acceptable to all in the community and add it to home page and a link should be going out with every mail on mailing list 

http://www.lug-iitd.org/Mailing_List_Guidelines
https://fedoraproject.org/wiki/Mailing_list_guidelines

**Comment by theskumar** [comment]
I've created new repo to curating the guidelines for pydelhi mailinglist. The guidelines will be available at https://pydelhi.org/mailing-list-guidelines, we can add that link to this repo as the guidelines[1] after it's release 0.1.0[2]

Everyone is welcome to send a PR to the it.

Footnotes:
[1] https://github.com/pydelhi/pydelhi.github.io#hosting-new-thingssub-site-under-banner-of-pydelhiorg 
[2] https://github.com/pydelhi/mailing-list-guidelines/issues/1
[3] https://github.com/pydelhi/mailing-list-guidelines/
